api_key = "<your_api_key_here>"
url = "https://<your_instance_address_here>:443/Beyondtrust/api/public/v3"
api_account_name = "<your_api_account_name_here>"
client_certificates_folder_path = "<your_certificates_folder_path_here>"
client_certificate_name = "<your_certificate_name_here>"
client_certificate_password = "<your_certificate_password_here>"