api_key = "<your_api_key>"
url = "https://example.com/Beyondtrust/api/public/v3"
api_account_name = "<your_api_key_user>"
client_certificates_folder_path = ""
client_certificate_name = ""
client_certificate_password = ""
client_id = "<your_client_id>"
client_secret = "<your_client_secret>"