# create managed system by workgroup id / API Version: 3.0
resource "passwordsafe_managed_system_by_workgroup" "managed_system_by_workgroup" {
  workgroup_id                           = "55"
  entity_type_id                         = 1
  host_name                              = "example-host"
  ip_address                             = "222.222.222.22"
  dns_name                               = "example.local"
  instance_name                          = "example-instance"
  is_default_instance                    = true
  template                               = "example-template"
  forest_name                            = "example-forest"
  use_ssl                                = false
  platform_id                            = 2
  netbios_name                           = "EXAMPLE"
  contact_email                          = "admin@example.com"
  description                            = "managed_system_by_workgroup"
  port                                   = 5432
  timeout                                = 30
  ssh_key_enforcement_mode               = 0
  password_rule_id                       = 0
  dss_key_rule_id                        = 0
  login_account_id                       = 0
  account_name_format                    = 1
  oracle_internet_directory_id           = "example-dir-id"
  oracle_internet_directory_service_name = "example-service"
  release_duration                       = 60
  max_release_duration                   = 120
  isa_release_duration                   = 30
  auto_management_flag                   = false
  functional_account_id                  = 0
  elevation_command                      = "sudo su -"
  check_password_flag                    = true
  change_password_after_any_release_flag = false
  reset_password_on_mismatch_flag        = true
  change_frequency_type                  = "last"
  change_frequency_days                  = 7
  change_time                            = "02:00"
  access_url                             = "https://example.com"
}

# create managed system by workgroup id / API Version: 3.1
resource "passwordsafe_managed_system_by_workgroup" "managed_system_by_workgroup" {
   workgroup_id                           = "55"
  entity_type_id                         = 1
  host_name                              = "example-host"
  ip_address                             = "222.222.222.22"
  dns_name                               = "example.local"
  instance_name                          = "example-instance"
  is_default_instance                    = true
  template                               = "example-template"
  forest_name                            = "example-forest"
  use_ssl                                = false
  platform_id                            = 2
  netbios_name                           = "EXAMPLE"
  contact_email                          = "admin@example.com"
  description                            = "managed_system_by_workgroup"
  port                                   = 5432
  timeout                                = 30
  ssh_key_enforcement_mode               = 0
  password_rule_id                       = 0
  dss_key_rule_id                        = 0
  login_account_id                       = 0
  account_name_format                    = 1
  oracle_internet_directory_id           = "example-dir-id"
  oracle_internet_directory_service_name = "example-service"
  release_duration                       = 60
  max_release_duration                   = 120
  isa_release_duration                   = 30
  auto_management_flag                   = false
  functional_account_id                  = 0
  elevation_command                      = "sudo su -"
  check_password_flag                    = true
  change_password_after_any_release_flag = false
  reset_password_on_mismatch_flag        = true
  change_frequency_type                  = "last"
  change_frequency_days                  = 7
  change_time                            = "02:00"
  access_url                             = "https://example.com"
  remote_client_type                     = "ssh"
}

# create managed system by workgroup id / API Version: 3.2
resource "passwordsafe_managed_system_by_workgroup" "managed_system_by_workgroup" {
   workgroup_id                           = "55"
  entity_type_id                         = 1
  host_name                              = "example-host"
  ip_address                             = "222.222.222.22"
  dns_name                               = "example.local"
  instance_name                          = "example-instance"
  is_default_instance                    = true
  template                               = "example-template"
  forest_name                            = "example-forest"
  use_ssl                                = false
  platform_id                            = 2
  netbios_name                           = "EXAMPLE"
  contact_email                          = "admin@example.com"
  description                            = "managed_system_by_workgroup"
  port                                   = 5432
  timeout                                = 30
  ssh_key_enforcement_mode               = 0
  password_rule_id                       = 0
  dss_key_rule_id                        = 0
  login_account_id                       = 0
  account_name_format                    = 1
  oracle_internet_directory_id           = "example-dir-id"
  oracle_internet_directory_service_name = "example-service"
  release_duration                       = 60
  max_release_duration                   = 120
  isa_release_duration                   = 30
  auto_management_flag                   = false
  functional_account_id                  = 0
  elevation_command                      = "sudo su -"
  check_password_flag                    = true
  change_password_after_any_release_flag = false
  reset_password_on_mismatch_flag        = true
  change_frequency_type                  = "last"
  change_frequency_days                  = 7
  change_time                            = "02:00"
  access_url                             = "https://example.com"
  remote_client_type                     = "ssh"
  application_host_id                    = 5001
  is_application_host                    = false
}

# create managed system by workgroup id / API Version: 3.3
resource "passwordsafe_managed_system_by_workgroup" "managed_system_by_workgroup" {
  workgroup_id                           = "55"
  entity_type_id                         = 1
  host_name                              = "example-host"
  ip_address                             = "222.222.222.22"
  dns_name                               = "example.local"
  instance_name                          = "example-instance"
  is_default_instance                    = true
  template                               = "example-template"
  forest_name                            = "example-forest"
  use_ssl                                = false
  platform_id                            = 2
  netbios_name                           = "EXAMPLE"
  contact_email                          = "admin@example.com"
  description                            = "managed_system_by_workgroup"
  port                                   = 5432
  timeout                                = 30
  ssh_key_enforcement_mode               = 0
  password_rule_id                       = 0
  dss_key_rule_id                        = 0
  login_account_id                       = 0
  account_name_format                    = 1
  oracle_internet_directory_id           = "example-dir-id"
  oracle_internet_directory_service_name = "example-service"
  release_duration                       = 60
  max_release_duration                   = 120
  isa_release_duration                   = 30
  auto_management_flag                   = false
  functional_account_id                  = 0
  elevation_command                      = "sudo su -"
  check_password_flag                    = true
  change_password_after_any_release_flag = false
  reset_password_on_mismatch_flag        = true
  change_frequency_type                  = "last"
  change_frequency_days                  = 7
  change_time                            = "02:00"
  access_url                             = "https://example.com"
  remote_client_type                     = "ssh"
  application_host_id                    = 5001
  is_application_host                    = false
}