name: Automation Tests

on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  automation-test:
    name: Automation Tests
    runs-on: ubuntu-latest  # Specify the operating system for the job's virtual machine
    steps:

      - name: Trigger existing-instance-trigger.yml
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1  
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'BeyondTrust',
              repo: 'ps-integration-test-automation',
              workflow_id: 'existing-instance-trigger.yml',
              ref: 'main',
              inputs: {
                customerkey: '${{ github.event.inputs.customerkey }}',
                integration: 'terraform',
                allowed_ips: '134.238.247.191,134.238.247.192,10.0.0.0/8',
                repo_path: 'eng-tf-provider-dev-local/beyondtrust/passwordsafe/terraform-provider-passwordsafe/v1.0.5/terraform-provider-passwordsafe_1.0.5_linux_amd64.zip',
                os_type: 'linux'
              }
            })