name: Automation Tests

env:
  TESTS_REPO: ${{ vars.TEST_REPO }}
  TESTS_WORKFLOW: 'dependabot-workflow.yml'
  TESTS_REF: 'main'
  JFROG_SERVER: ${{ secrets.JFROG_SERVER }}

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_origin:
        description: 'Origin of the build to test'
        required: true
        type: string
        default: 'DEV'

jobs:
  automation-test-run:
    name: Automation Tests
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.check_run.outputs.conclusion }}
      url: ${{ steps.check_run.outputs.url }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Retrieve version
        id: info
        run: |
          echo "version=$(grep -oP '[\d]+\.[\d]+\.[\d]+' version.txt)" >> $GITHUB_OUTPUT

      - name: Checking if there Automation tests running
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1  
        with:
          github-token: ${{ secrets.AUTOMATION_PAT }}
          script: |
            var workflow = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
              owner: context.repo.owner,
              repo: '${{ env.TESTS_REPO }}',
              event: 'workflow_dispatch'
            });

            while (!workflow.data.workflow_runs || workflow.data.workflow_runs.length === 0) {
              // No workflow runs found yet, wait and retry
              await new Promise(resolve => setTimeout(resolve, 5000));
              workflow = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
                owner: context.repo.owner,
                repo: '${{ env.TESTS_REPO }}',
                event: 'workflow_dispatch'
              });
            }

            var status = workflow.data.workflow_runs[0].status;

            while(status === 'in_progress' || status === 'queued'){
              workflow = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
                owner: context.repo.owner,
                repo: '${{ env.TESTS_REPO }}',
                event: 'workflow_dispatch'
              });

              status = workflow.data.workflow_runs[0].status;
              await new Promise(resolve => setTimeout(resolve, 200000));
            }

      - name: 'Triggering Automation tests workflow'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1  
        with:
          github-token: ${{ secrets.AUTOMATION_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: '${{ env.TESTS_REPO}}',
              workflow_id: '${{ env.TESTS_WORKFLOW }}',
              ref: '${{ env.TESTS_REF }}',
              inputs: {
                integration: 'terraform',
                env: '${{ github.event.inputs.build_origin || 'DEV' }}',
                build_version: '${{ steps.info.outputs.version }}',
                os_type: 'linux'
              }
            })

      - name: Wait until workflow information is available
        run: sleep 10s

      - name: Checking Automation tests workflow's status
        id: check_run
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1  
        with:
          github-token: ${{ secrets.AUTOMATION_PAT }}
          script: |
            var status;
            var conclusion;
            var id;

            while(status != 'completed'){
              const workflow = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
                owner: context.repo.owner,
                repo: '${{ env.TESTS_REPO }}',
                event: 'workflow_dispatch'
              });

              if (!workflow.data.workflow_runs || workflow.data.workflow_runs.length === 0) {
                // No workflow runs found yet, wait and retry
                await new Promise(resolve => setTimeout(resolve, 5000));
                continue;
              }

              status = workflow.data.workflow_runs[0].status;
              conclusion = workflow.data.workflow_runs[0].conclusion;
              id = workflow.data.workflow_runs[0].id;

              await new Promise(resolve => setTimeout(resolve, 180000));
            }

            const workflow_run = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}', {
              owner: context.repo.owner,
              repo: '${{ env.TESTS_REPO }}',
              run_id: id,
            });

            core.setOutput("conclusion", conclusion);
            core.setOutput("url", workflow_run.data.html_url);

  automation-test-PR:
    name: Publish automation test results on PR 
    needs: [automation-test-run]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      actions: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Make comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            var output;
            var url = '${{ needs.automation-test-run.outputs.url }}';
            var conclusion = '${{ needs.automation-test-run.outputs.conclusion }}';
            
            if (conclusion === 'success') {
              output = `## Automation tests Checked

              ### Automation tests are **successful** 
              `;
              output+="\nPlease check the Automation tests run [here]("+url+")";
            } else {
              output = `## Automation tests Checked

              ### Automation tests **failed**`;
              output+="\nPlease check the Automation tests run [here]("+url+")";
            } 

            const fs = require('fs');
            fs.writeFile('message.txt', output, (err) => {
              if (err) throw err;
            });

      - name: Post Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message-path: |
            message.txt
        
      - name: Set state for Automation test workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            var conclusion = '${{ needs.automation-test-run.outputs.conclusion }}';
            if (conclusion != 'success') {
              core.setFailed(`Automation tests fail, please refer to PR comment for details`);
            }

  automation-test-no-pr:
    name: Publish automation test result for other events than PRs
    needs: [automation-test-run]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          
      - name: Set state for Automation test workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            var output;
            var url = '${{ needs.automation-test-run.outputs.url }}';
            var conclusion = '${{ needs.automation-test-run.outputs.conclusion }}';
            if (conclusion != 'success') {
              output = "Automation tests fail, please check the Automation tests run here: "+url;
              core.setFailed(output);
            }
