name: Code coverage report on PR

on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
      branches:
        - 'main'
    workflow_dispatch:

permissions:
  contents: write

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: |
          export TF_ACC=1
          go mod tidy
          go test -cover -coverprofile=coverage.txt ./...
          ls -alt
        working-directory: providers
      
      - name: Save unit tests coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage
          path: providers/coverage.txt        

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: unit_test 
    permissions:
      contents: read
      actions: read  
      pull-requests: write 
    steps:
      - uses: fgrosse/go-coverage-report@8c1d1a09864211d258937b1b1a5b849f7e4f2682 # v1.2.0
        with:
            coverage-artifact-name: "coverage" 
            coverage-file-name: "coverage.txt"   