name: PR/item link check

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  call-workflow:
    uses: BeyondTrust/beyondinsight-actions/.github/workflows/enforce-pr-issue-link.yml@main