name: Build promotion

on:
  workflow_dispatch:

permissions: {}

jobs:
  promote:
    name: Promote
    uses: BeyondTrust/workflows/.github/workflows/promote-jfrog-build.yaml@5254e0f517ab7dfc5a9a7c56ae2963342cd2ebd8 # v4.7.0
    secrets: inherit
    with:
      generic_type: "terraform"
