# Terraform Provider release workflow.
name: Release
env:
  JFROG_SERVER: eng-tf-provider-dev-local
  JFROG_CLI_BUILD_NAME: ${{ github.event.repository.name }}
  SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions: {}

jobs:
  unit_test:
    name: Unit Testing
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: project

