name: SonarQube

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      - name: Run unit tests
        run: |
          export TF_ACC=1
          go mod tidy
          go test ./providers/... -cover -coverprofile=coverage.out -v
          go tool cover -func="coverage.out"

      - name: Save unit tests coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: coverage.out

  sonarqube:
    needs: [unit-tests]
    uses: BeyondTrust/workflows/.github/workflows/sonarqube.yaml@51e9f52f8446a28edae9c7277ce1a612b86570ea # v4.13.1
    permissions:
      actions: read
      contents: read
      pull-requests: write
    with:
      coverage_artifact: coverage-report
      coverage_artifact_path: .
      required_coverage_files: coverage.out
      extra_flags: >-
        -Dsonar.exclusions=**/*_test.go
        -Dsonar.go.coverage.reportPaths=coverage.out
    secrets: inherit
